batch_size: 16
checkpoints_path: null
generation: null
logging:
  hub_repo_details: null
  hub_repo_results: null
  hub_repo_tensorboard: HuggingFaceBR4/thomwolf-webdata-std-two
  local_output_path: /scratch/thomwolf/lighteval/webdata-std-two-1p82G-CC-MAIN-2020-05-no-dedup-seed-42-const_lr_2294060
  push_details_to_hub: false
  push_results_to_hub: false
  push_results_to_tensorboard: true
  tensorboard_metric_prefix: e
parallelism:
  dp: 8
  expert_parallel_size: 1
  pp: 1
  pp_engine: 1f1b
  tp: 1
  tp_linear_async_communication: false
  tp_mode: ALL_REDUCE
slurm_script_dir: /fsx/thomwolf/logs_evals/
slurm_template: /fsx/thomwolf/github/brrr/examples/thomwolf/run_eval.slurm.jinja
tasks:
  custom_tasks: brrr.lighteval.evaluation_tasks
  dataset_loading_processes: 8
  max_samples: 1000
  multichoice_continuations_start_space: null
  no_multichoice_continuations_start_space: null
  num_fewshot_seeds: null
  tasks: early-signal
